#!/bin/bash
PROCENT=5
RUN=0
function USAGE {
	echo -e "Usage: $0 [FLAGS]... [BITHORDE LINK FILE]\n\n  -h, --help     Shows this help.\n  -p, --play     Opens file with xdg-open after delay. (DEFAULT: No)\n  -d, --delay    Wait [SECONDS] before open with xdg-open. (DEFAULT: 20)\n"
}
if [ "$1" = "" ]; then
        echo "bhbuff requires following arguments..."
	USAGE
        exit 1
fi
while [ $# -gt 0 ]; do 
  case "$1" in
    -h|--help)
	      USAGE
	      exit 0
	      ;;
    -r|--run)
              RUN=1
              ;;
    -p|--procent)
              PROCENT="$2"
              if [[ "$PROCENT" =~ ^[0-9]+$ ]]; then
			if [ "$PROCENT" -ge 100 ]; then
				PROCENT=100
			fi
		else
                	echo "Procent needs to be a number between 1 - 100..."
			USAGE
                	exit 1
              fi
              ;;
    *)
              FILE=${!#}
	      if ! [[ $(readlink "$FILE") == *magnet* ]]; then
		echo "File not a bithorde symlink..."
		USAGE
		exit 1
	      fi
		
	      ;;
  esac
  shift
done
PIECETOLOAD="$(($(($(($(stat -L -c%s "$FILE")/100))*$PROCENT))/512))"
echo "dd if="$FILE" of=/dev/null bs=512 count=$PIECETOLOAD"
dd if="$FILE" of=/dev/null bs=512 count=$PIECETOLOAD
#bhget -sy -py "$FILE" > /dev/null &
#BHGETPID=$!
#echo -e "BHGETPID: $BHGETPID\n"
#trap "echo -e '\nKilling script and its childs...';kill $BHGETPID; exit 130" SIGINT SIGTERM
if [ "$RUN" = 1 ]; then
	sleep $DELAY
	xdg-open "$FILE" > /dev/null 2> /dev/null
	dd if="$FILE" of=/dev/null bs=512 count=$PIECETOLOAD
fi
