#!/bin/bash
PERCENT=10
RUN=1
function USAGE {
	echo -e "
Usage: $0 [FLAGS]... [BITHORDE LINK FILE]\n
  -h, --help        Shows this help.
  -p, --percent     Load asset [NUM] percent. (DEFAULT: 10)
  -n, --norun       Don\'t open asset with xdg-open after preload. (DEFAULT: Open asset after preload)\n
  Example: $0 -p 50 -n MyBithordeLink.avi\n"
}
if [ "$1" = "" ]; then
        echo "bhbuff needs a bithorde link to handle..."
	USAGE
        exit 1
fi
while [ $# -gt 0 ]; do 
  case "$1" in
    -h|--help)
	      USAGE
	      exit 0
	      ;;
    -n|--norun)
              RUN=0
              ;;
    -p|--percent)
              PERCENT="$2"
              if [[ "$PERCENT" =~ ^[0-9]+$ ]]; then
			if [ "$PERCENT" -ge 100 ]; then
				PERCENT=100
			fi
		else
                	echo "Procent needs to be a number between 1 - 100..."
			USAGE
                	exit 1
              fi
              ;;
    *)
              FILE=${!#}
	      if ! [[ $(readlink "$FILE") == *magnet* ]]; then
		echo "File not a bithorde symlink..."
		USAGE
		exit 1
	      fi
		
	      ;;
  esac
  shift
done
PIECETOLOAD="$(($(($(($(stat -L -c%s "$FILE")/100))*$PERCENT))/512))"
dd if="$FILE" of=/dev/null bs=512 count=$PIECETOLOAD
if [ "$RUN" = 1 ]; then
	xdg-open "$FILE" > /dev/null 2> /dev/null
	dd if="$FILE" of=/dev/null bs=512 skip=$PIECETOLOAD
fi
